---
input:
  filepath: "./downlinks.json"
general:
  encoding: "utf-8"
logging:
  encoding: "utf-8"
  fileHandler:
    logsDirectory: "./logs"
    filenameFormat: "%Y-%m-%d--%H-%M-%S" # -> ./logs/<datetime>.log
    logLevel: "DEBUG" # INFO | WARNING | ERROR | CRITICAL | DEBUG
    formatter: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  streamHandler:
    console: "stdout" # stderr | stdout
    logLevel: "INFO" # INFO | WARNING | ERROR | CRITICAL | DEBUG
    formatter: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
client:
  enableEnvVars: false
  insecure: true
  encoding: "utf-8"
  timeouts:
    connect: 5.0
    read: 5.0
    write: 5.0
    pool: 5.0
